<a href="https://colab.research.google.com/github/EhsanGhasemi423/INFS-8368/blob/main/3_Tools_from_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Most everyday mathematics consists of manipulating numbers one at a time. Formally, we call these values scalars.

We denote scalars by ordinary lower-cased letters (e.g., x, y, and z )

**Scalars** are implemented as tensors that contain only one element. Below, we assign two scalars and perform the familiar addition, multiplication, division, and exponentiation operations.

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.constant(3.0)
y = tf.constant(2.0)

x + y, x * y, x / y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=5.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)

In [ ]:
print(type(x))

<class 'tensorflow.python.framework.ops.EagerTensor'>


For current purposes, you can think of a **vector** as a fixed-length array of scalars.

As with their code counterparts, we call these scalars the elements of the vector (synonyms include entries and components).

When vectors represent examples from real-world datasets, their values hold some real-world significance. For example, if we were training a model to predict the risk of a loan defaulting, we might associate each applicant with a vector whose components correspond to quantities like their income, length of employment, or number of previous defaults. If we were studying the risk of heart attack, each vector might represent a patient and its components might correspond to their most recent vital signs, cholesterol levels, minutes of exercise per day, etc. We denote vectors by bold lowercase letters, (e.g., **x**, **y**, and **z**).


Vectors are implemented as 1st-order tensors (i.e., 1-dimensional tensor or rank-1 tensor).In Python, as in most programming languages, vector indices start at 0, also known as zero-based indexing, whereas in linear algebra subscripts begin at 1 (one-based indexing).

In [ ]:
x = tf.range(3)
x, x[2],len(x)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 3)

We can also access the length via the shape attribute. The shape is a tuple that indicates a tensor’s length along each axis. Tensors with just one axis have shapes with just one element.

we use order to refer to the number of axes and dimensionality exclusively to refer to the number of components.

In [ ]:
x.shape

TensorShape([3])

Just as scalars are 0th-order tensors and vectors are 1st-order tensors, matrices are 2nd-order tensors. We denote matrices by bold capital letters (e.g., **X**, **Y**, and **Z**), and represent them in code by tensors with two axes.

A matrix can have any number of rows and columns. If the number of rows is the same as the number of columns, it is called a square matrix. To identify a specific value inside a matrix, we specify both its row and its column. For example, we might refer to the value in the second row and third column of the matrix.

We can convert any appropriately sized m * n tensor into an m*n matrix by passing the desired shape to **reshape**:

In [ ]:
A = tf.reshape(tf.range(6), (3, 2))
A

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
A[1,0]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
A.shape

TensorShape([3, 2])

Sometimes we want to flip the axes. When we exchange a matrix’s rows and columns, the result is called its **transpose**.

In code, we can access any matrix’s transpose as follows:

In [ ]:
tf.transpose(A)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 2, 4],
       [1, 3, 5]], dtype=int32)>

**Symmetric** matrices are the subset of square matrices that are equal to their own transposes.

In [ ]:
A = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == tf.transpose(A)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

In [ ]:
A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]], dtype=int32)>

Matrices are useful for representing datasets. Typically, rows correspond to individual records and columns correspond to distinct attributes.

**Tensors**

A **tensor** is a generalization of scalars, vectors, and matrices to higher dimensions.

Tensors can have any number of axes (dimensions).

They are the primary data structure used in machine learning frameworks such as TensorFlow and PyTorch.

Scalars, vectors, and matrices are special cases of tensors:
  0th-order tensor: Scalar (single value)
  1st-order tensor: Vector (1D array)
  2nd-order tensor: Matrix (2D table)
  3rd-order tensor: Image (height × width × color channels)
  4th-order tensor: Collection (batch) of images

Higher-order tensors are created by adding more dimensions, allowing complex data (e.g., images, videos, and batches of data) to be represented efficiently.




In [ ]:
tf.reshape(tf.range(24), (2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

Scalars, vectors, matrices, and higher-order tensors all have some handy properties. For example, **elementwise operations** produce outputs that have the same shape as their operands.

In [ ]:
A = tf.reshape(tf.range(6, dtype=tf.float32), (2, 3))
B = A  # No cloning of A to B by allocating new memory
A, A + B

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]], dtype=float32)>)

The elementwise product of two matrices is called their **Hadamard product** (denoted ⊙).

The name Hadamard comes from the French mathematician Jacques Hadamard, who studied this type of operation.

In [ ]:
A * B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]], dtype=float32)>

Adding or multiplying a **scalar** and a tensor produces a result with **the same shape** as the **original tensor**. Here, each element of the tensor is added to (or multiplied by) the scalar.

In [ ]:
a = 2
X = tf.reshape(tf.range(24), (2, 3, 4))
a + X, (a * X).shape


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]], dtype=int32)>,
 TensorShape([2, 3, 4]))

There is a simple function to calculate the **sum** of a **tensor’s elements**.

A tensor can have many dimensions (axes). Summing over all axes means adding every number in the tensor into one total.

In [ ]:
x = tf.range(3, dtype=tf.float32)
x, tf.reduce_sum(x)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 2.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0>)

In [ ]:
A.shape, tf.reduce_sum(A)

(TensorShape([2, 3]), <tf.Tensor: shape=(), dtype=float32, numpy=15.0>)

By default, tf.reduce_sum() adds all the elements in a tensor and returns a single value (a scalar). You can also specify an axis to sum along. When you sum along **axis=0**, TensorFlow **adds the values in each column**. Since the rows are combined into one value per column, the row dimension (axis 0) is removed from the output shape.

In [ ]:
A.shape, tf.reduce_sum(A, axis=0).shape

(TensorShape([2, 3]), TensorShape([3]))

axis=0 is being removed after the summation.

In [ ]:
G = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print(G.shape)

print(tf.reduce_sum(G, axis=0))

print(tf.reduce_sum(G, axis=0).shape)

(2, 3)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
(3,)


axis=1 sums the values in each row, producing one value per row.

In [ ]:
import tensorflow as tf

H = tf.constant([
    [2, 4, 6],
    [1, 3, 5]
])

print(H.shape)

print(tf.reduce_sum(H, axis=1))

print(tf.reduce_sum(H, axis=1).shape)

(2, 3)
tf.Tensor([12  9], shape=(2,), dtype=int32)
(2,)


Reducing a matrix along both rows and columns via summation is equivalent to summing up all the elements of the matrix.

In [ ]:
tf.reduce_sum(A, axis=[0, 1]), tf.reduce_sum(A)  # Same as tf.reduce_sum(A)

(<tf.Tensor: shape=(), dtype=float32, numpy=15.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=15.0>)

A related quantity is the **mean**, also called the average. We calculate the mean by dividing the sum by the total number of elements. Because computing the mean is so common, it gets a dedicated **library function** that works analogously to sum.

In [ ]:
tf.reduce_mean(A), tf.reduce_sum(A) / tf.size(A).numpy()

(<tf.Tensor: shape=(), dtype=float32, numpy=2.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.5>)

Normally, reduce_sum() removes a dimension. If you set **keepdims=True**, TensorFlow keeps that dimension so the result is easier to use in later calculations, such as dividing the original matrix by its row sums.

keepdims=True **keeps the reduced dimension** instead of removing it.

In [ ]:
A.shape

TensorShape([2, 3])

In [ ]:
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A, sum_A.shape

(<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[ 3.],
        [12.]], dtype=float32)>,
 TensorShape([2, 1]))

A cumulative sum adds values one at a time, keeping a running total. Unlike reduce_sum(), it does not reduce the size of the tensor.

In [ ]:
I = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print(tf.cumsum(I, axis=0))

tf.Tensor(
[[1 2 3]
 [5 7 9]], shape=(2, 3), dtype=int32)



**Dot Product**


A **dot product** multiplies the corresponding elements of two vectors and then adds the results together. The final answer is a single number (a scalar).

In [ ]:
y = tf.ones(3, dtype=tf.float32)
x, y, tf.tensordot(x, y, axes=1)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 1., 2.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.0>)

Equivalently, we can calculate the dot product of two vectors by performing an elementwise multiplication followed by a sum:

In [ ]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

Dot products have many practical applications. They are commonly used to compute weighted sums and weighted averages, measure the similarity between vectors, and form the basis of many machine learning algorithms.

**Matrix–Vector Products**

A matrix–vector product is made by taking the dot product of each row of the matrix with the vector.

Matrix×Vector=New Vector

To express a matrix–vector product in code, we use the **matvec** function.

Note that the **column dimension of A** (its length along axis 1) must be the **same** as **the dimension of x (its length)**.

In [ ]:
A.shape, x.shape, tf.linalg.matvec(A, x)

(TensorShape([2, 3]),
 TensorShape([3]),
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 5., 14.], dtype=float32)>)

**linalg** stands for linear algebra. It is the TensorFlow module that contains functions for matrix and vector operations.

**Matrix–Matrix Multiplication**

1. Multiply a **row** from **matrix A** with a **column** from **matrix B** using the **dot product**.

2. Each dot product becomes one element in the output matrix.

3. Repeat for **every row and every column**.

**Shape rule:**

(m×n)(n×p)→(m×p)


The number of columns in A must equal the number of rows in B.

In [ ]:
B = tf.ones((3, 4), tf.float32)

A,B, tf.matmul(A, B)


(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]], dtype=float32)>)

**Norms**

A norm measures the length (or magnitude) of a vector.

The **most common norm is the L2** norm (Euclidean norm), which is the straight-line distance from the origin to the vector.

It is the distance from the origin (0,0) to the tip of the vector.

Just like finding the hypotenuse of a right triangle, the L2 norm uses the Pythagorean theorem:

$$
\|\mathbf{x}\|_2 =
\sqrt{x_1^2 + x_2^2 + \cdots + x_n^2}
$$

In [ ]:
u = tf.constant([3.0, -4.0])
tf.norm(u)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

**L1 Norm (Manhattan Distance)**

Definition: The L1 norm is the sum of the absolute values of a vector's elements.
$$
\|\mathbf{x}\|_1=\sum_{i=1}^{n}|x_i|
$$

The L1 norm is computed by taking the absolute value of each element and then summing them.

In [ ]:
tf.reduce_sum(tf.abs(u))

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

**Matrix Norms**


Just as vectors have norms, matrices also have norms.

The most common matrix norm is the Frobenius norm, which measures the size of a matrix.

$$
\|\mathbf{X}\|_F =
\sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n} x_{ij}^{2}}
$$

How to compute it:
1. Square every element.
2. Add all the squared values.
3. Take the square root.

$$
X=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

$$
\|\mathbf{X}\|_F
=
\sqrt{1^2+2^2+3^2+4^2}
=
\sqrt{30}
\approx5.48
$$

The **Frobenius** norm is the **L2 norm applied to all the elements of a matrix**.





In [ ]:
tf.norm(tf.ones((4, 9)))

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

## **Why Are Norms Important?**

Norms measure the size of a vector or matrix and the distance between predictions and actual values.

In machine learning and deep learning, norms are widely used to:

1. Measure prediction error (loss functions)
2. Measure similarity or distance between data points
3. Regularize models to reduce overfitting (L1 and L2 regularization)
4. Define optimization objectives that algorithms minimize during training

During training, machine learning models often minimize a norm (or a function based on a norm) to improve performance.

In deep learning, we are often trying to solve optimization problems: **maximize** the probability assigned to observed data; **maximize** the revenue associated with a recommender model; **minimize** the distance between predictions and the ground truth observations; **minimize** the distance between representations of photos of the same person while **maximizing** the distance between representations of photos of different people.

These **distances**, which constitute the objectives of deep learning algorithms, are often **expressed as norms**.